# Generated by Django 4.2.30 on 2026-06-05 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0006_load_total_picked_alter_load_consolidated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hb_bd', models.CharField(blank=True, max_length=10)),
                ('store_id_raw', models.CharField(blank=True, max_length=20)),
                ('store_name_raw', models.CharField(blank=True, max_length=200)),
                ('ordered', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('pick_carryover', models.IntegerField(default=0)),
                ('doors', models.CharField(blank=True, max_length=50)),
                ('open_status', models.CharField(blank=True, max_length=20)),
                ('closed_status', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('window', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('mergers', models.CharField(blank=True, max_length=100)),
                ('loaders', models.CharField(blank=True, max_length=100)),
                ('check_field', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_plans', to='transport.store')),
            ],
            options={
                'ordering': ['date', 'store_name_raw'],
                'unique_together': {('date', 'store_id_raw')},
            },
        ),
    ]
