# Generated by Django 4.2.30 on 2026-06-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplan',
            options={'ordering': ['date', 'row_order', 'store_name_raw']},
        ),
        migrations.RenameField(
            model_name='dailyplan',
            old_name='pick_carryover',
            new_name='row_order',
        ),
    ]
