# Generated by Django 4.2.30 on 2026-06-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyplan', '0002_alter_dailyplan_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('date', 'store_id_raw', 'hb_bd')},
        ),
    ]
