# Generated by Django 4.2.30 on 2026-06-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyplan', '0003_alter_dailyplan_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='flag_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
