# Generated by Django 4.2.30 on 2026-06-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('store_code', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
                ('del_type', models.CharField(blank=True, choices=[('', '—'), ('HB', 'HB'), ('BD', 'BD'), ('MID', 'MID')], max_length=10)),
                ('split_full', models.CharField(choices=[('Full', 'Full'), ('Split', 'Split')], default='Full', max_length=10)),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('store_code', models.CharField(blank=True, max_length=20)),
                ('final_plt', models.IntegerField(blank=True, null=True)),
                ('bay', models.CharField(blank=True, max_length=20)),
                ('time_arrive', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('schedule_eta', models.CharField(blank=True, max_length=50)),
                ('date_departed', models.DateField(blank=True, null=True)),
                ('trailer_no', models.CharField(blank=True, max_length=50)),
                ('consolidated', models.CharField(blank=True, max_length=100)),
                ('revised_eta', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Loaded', 'Loaded'), ('On the Load', 'On the Load'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('row_color', models.CharField(blank=True, choices=[('', 'None'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('lightblue', 'Light Blue'), ('lightgreen', 'Light Green')], default='', max_length=20)),
                ('pre_checked_load', models.CharField(blank=True, max_length=200)),
                ('supervisor_checked', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='transport.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='transport.driver')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='transport.store')),
            ],
            options={
                'ordering': ['date', 'departure_time'],
            },
        ),
    ]
