# Generated by Django 4.2.30 on 2026-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='del_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('HB', 'HB'), ('BD', 'BD'), ('MID', 'MID'), ('HD', 'HD')], max_length=10),
        ),
    ]
