# Generated by Django 4.2.30 on 2026-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_load_del_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='time_departed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='consolidated',
            field=models.CharField(blank=True, choices=[('', '—'), ('Loaded', 'Loaded'), ('On the Load', 'On the Load'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
