# Generated by Django 4.2.30 on 2026-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_load_time_departed_alter_load_consolidated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='consolidated',
            field=models.CharField(blank=True, choices=[('', '—'), ('Loaded', 'Loaded'), ('On the Load', 'On the Load'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Consolidated', 'Consolidated')], max_length=100),
        ),
    ]
