# Generated by Django 4.2.30 on 2026-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_load_consolidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='consolidated',
            field=models.CharField(blank=True, choices=[('', '—'), ('Loaded', 'Loaded'), ('On the Load', 'On the Load'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Consolidated', 'Consolidated'), ('Wrapped and Ready to Load', 'Wrapped and Ready to Load')], max_length=100),
        ),
    ]
