# Generated by Django 4.2.30 on 2026-06-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_load_consolidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='total_picked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='consolidated',
            field=models.CharField(blank=True, choices=[('', '—'), ('Loaded', 'Loaded'), ('On the Load', 'On the Load'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Consolidated', 'Consolidated'), ('Wrapped and Ready to Load', 'Wrapped and Ready to Load'), ('Waiting on Load', 'Waiting on Load')], max_length=100),
        ),
    ]
